symptoms=['Fatigue (Mild)',
'Fatigue (Moderate)',
'Fatigue (Severe)',
'Voice irritation (Mild)',
'Voice irritation (Moderate)',
'Voice irritation (Severe)',
'Sinus congestion (Mild)',
'Sinus congestion (Moderate)',
'Sinus congestion (Severe)',
'Indigestion (Mild)',
'Indigestion (Moderate)',
'Indigestion (Severe)',
'Stomachache (Mild)',
'Stomachache (Moderate)',
'Stomachache (Severe)',
'Diarrhea (Mild)',
'Diarrhea (Moderate)',
'Diarrhea (Severe)',
'Constipation (Mild)',
'Constipation (Moderate)',
'Constipation (Severe)',
'Bloating (Mild)',
'Bloating (Moderate)',
'Bloating (Severe)',
'Hay Fever (Mild)',
'Hay Fever (Moderate)',
'Hay Fever (Severe)',
'Dandruff (Mild)',
'Dandruff (Moderate)',
'Dandruff (Severe)',
'Acne (Mild)',
'Acne (Moderate)',
'Acne (Severe)',
'Allergies (Mild)',
'Allergies (Moderate)',
'Allergies (Severe)'
]